import os
import json
from minify_html import minify
Import("env")


# Minify HTML and CSS
print("Processing pages")
with open("include/page_content.h", "w") as inc, os.scandir("pages") as sc:
    inc.write("// AUTO GENERATED BY BUILD SCRIPT\n#pragma once\n")
    for entry in sc:
        if entry.name.startswith(".") or not entry.is_file():
            continue
        if entry.name.endswith(".html"):
            page_type = "html"
        elif entry.name.endswith(".css"):
            page_type = "css"
        else:
            continue

        print(entry.name)

        with open(entry, "r") as f:
            original = f.read()
        if page_type == "html":
            # Make sure that %s in HTML attributes are quoted properly, since html_minify removes them
            minified = minify(original, minify_js=True, minify_css=True).replace("=%s", "=\"%s\"")
        else:
            # Wrap in a <style> tag so it recognizes the CSS, and then slice it out
            minified = minify(f"<style>{original}</style>", minify_css=True)[7:-8]
        # Use json.dumps to add quotes and escape characters etc
        inc.write(f"#define PAGE_CONTENT_{entry.name.upper().replace('.', '_')} {json.dumps(minified)}\n")
